# Generated by Django 4.0.3 on 2022-04-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='abc',
        ),
    ]
