# Generated by Django 4.0.3 on 2022-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questions_options_questions_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
                ('cholesterol', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'Well Above Normal')])),
                ('gluc', models.IntegerField(choices=[(1, 'Normal'), (2, 'Above Normal'), (3, 'Well Above Normal')])),
                ('smoke', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('alco', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('active', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('cardio', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='q',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
