# Generated by Django 4.0.3 on 2022-04-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userresponse_alter_questions_q'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
