# Generated by Django 4.0.3 on 2022-04-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='cardio',
        ),
    ]
