import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import s from "../public/circle.svg";
import setting from "../public/wheel.svg";
import { VictoryBar, VictoryChart, VictoryAxis, VictoryTheme } from "victory";
import useWindowDimensions from "./hooks/useWindowDimensions";
import DesktopNav from "./components/DesktopNav";
import MobileTopMenu from "./components/MobileTopMenu";
import MobileBottomNav from "./components/MobileBottomNav";
import UnicornIcon from "../public/unicornIcon.svg";
import Logo from "../public/Logo.svg";
import Form from "./form";
import { useState } from "react";
import Link from "next/link";

const data = [
  { time: 1, weight: 60 },
  { time: 2, weight: 60 },
  { time: 3, weight: 57 },
  { time: 4, weight: 57 },
];

const topMenu = (isDesktop: boolean) => {
  return isDesktop ? <DesktopNav /> : <MobileTopMenu />;
}; //why this doesn't work?

const goesUp = "opacity-0 translate-y-n-screen absolute w-full";
const goesDown = "opacity-0 translate-y-screen absolute w-full";
const present = "opacity-1 translate-y-0";

const getClassName = (activeStep: number, questionNumber: number) => {
  if (activeStep === questionNumber) return present;
  if (activeStep > questionNumber) return goesUp;
  else return goesDown;
};

const Home: NextPage = () => {
  const { height, width, isDesktop } = useWindowDimensions();

  const [step, setStep] = useState(1);

  const nextStep = () => setTimeout(() => setStep((step) => step + 1), 100);

  return (
    <div className="overflow-hidden max-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex flex-col items-center justify-center h-screen"
        onScroll={() => {
          nextStep();
        }}
      >
        <div>
          <div className="flex justify-center">
            <Image src={UnicornIcon} />
          </div>
          <div>
            <Image src={Logo} />
          </div>
          <p className="text-primary text-sm text-center">
            Your Personal Heath Asistant
          </p>
          <div className="flex justify-center mt-8" style={{borderRadius:"50%"}}>
            <button className="text-center bg-secondary text-white p-4" style={{borderRadius:"50%"}}>
              <Link href="form">
              Click
              </Link>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
