import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import s from "../public/circle.svg";
import setting from "../public/wheel.svg";
import { VictoryBar, VictoryChart, VictoryAxis, VictoryTheme } from "victory";
import useWindowDimensions from "./hooks/useWindowDimensions";
import DesktopNav from "./components/DesktopNav";
import MobileTopMenu from "./components/MobileTopMenu";
import MobileBottomNav from "./components/MobileBottomNav";

const data = [
  { time: 1, weight: 60 },
  { time: 2, weight: 60 },
  { time: 3, weight: 57 },
  { time: 4, weight: 57 },
];

const topMenu = (isDesktop: boolean) => {
  return isDesktop ? <DesktopNav /> : <MobileTopMenu />;
}; //why this doesn't work?

const Track: NextPage = () => {
  const { height, width, isDesktop } = useWindowDimensions();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isDesktop ? <DesktopNav /> : <MobileTopMenu />}
      <div className="flex justify-center bg-gray-100">
        <div className="bg-gray-100 min-h-screen flex flex-col items-center max-w-3xl justify-center">
          <main className="w-11/12">
            <section>
              <p className="mt-8">Summary</p>
              <article className="rounded-xl bg-white p-4 shadow-md">
                <div className="flex">
                  <div className="w-6/12 flex justify-center py-8">
                    <div className="w-8/12">
                      <VictoryBar data={data} x="time" y="weight" />
                    </div>
                  </div>
                  <div className="w-6/12 flex justify-center py-8">
                    <div className="w-8/12">
                      <VictoryBar data={data} x="time" y="weight" />
                    </div>
                  </div>
                </div>

                <div className="flex">
                  <div className="w-6/12 flex justify-center py-8">
                    <div className="w-8/12">
                      <VictoryBar data={data} x="time" y="weight" />
                    </div>
                  </div>
                  <div className="w-6/12 flex justify-center py-8">
                    <div className="w-8/12">
                      <VictoryBar data={data} x="time" y="weight" />
                    </div>
                  </div>
                </div>
              </article>

              <h1></h1>
              <p className="mt-8">Steps</p>
              <article className="rounded-xl bg-white p-4 shadow-md">
                <div className="flex">
                  <div className="w-6/12 flex justify-center items-center py-8">
                    <div className="w-8/12">
                      <div>
                        <span className="text-primary text-4xl">7000 </span>
                        steps
                      </div>
                      <b>Today</b>
                    </div>
                  </div>
                  <div className="w-6/12 flex justify-center py-8">
                    <div className="w-8/12">
                      <div>
                        <span className="text-primary text-4xl">6853 </span>
                        steps
                      </div>
                      <b>Avg. month</b>
                    </div>
                  </div>
                </div>
              </article>

              <p className="mt-8">Sleep</p>
              <article className="rounded-xl bg-white p-4 shadow-md">
                <div className="flex">
                  <div className="w-6/12 flex justify-center items-center py-8">
                    <div className="w-8/12">
                      <div>
                        <span className="text-primary text-4xl">8 </span>hours
                      </div>
                      <b>Today</b>
                    </div>
                  </div>
                  <div className="w-6/12 flex justify-center py-8">
                    <div className="w-8/12">
                      <div>
                        <span className="text-primary text-4xl">7.8 </span>hours
                      </div>
                      <b>Avg. month</b>
                    </div>
                  </div>
                </div>
              </article>
            </section>
          </main>

          {isDesktop ? null : <MobileBottomNav />}
        </div>
      </div>
    </div>
  );
};

export default Track;
